require('dotenv').config();
const mongoose = require('mongoose');
const Problem = require('./models/Problem');

const problems = [
  // ─── EASY ───────────────────────────────────────────────
  {
    title: 'Two Sum',
    slug: 'two-sum',
    description: 'Given an array of integers and a target, return the indices of the two numbers that add up to the target. Each input has exactly one solution and you may not use the same element twice.',
    difficulty: 'Easy', tags: ['Array', 'Hash Table'],
    constraints: ['2 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9', 'Only one valid answer exists'],
    examples: [{ input: 'nums = [2,7,11,15], target = 9', output: '[0,1]', explanation: 'nums[0] + nums[1] = 9' }],
    functionName: 'twoSum',
    testCases: [
      { input: '[[2,7,11,15],9]', output: '[0,1]', isHidden: false },
      { input: '[[3,2,4],6]', output: '[1,2]', isHidden: true },
      { input: '[[3,3],6]', output: '[0,1]', isHidden: true },
    ],
    starterCode: { javascript: 'function twoSum(nums, target) {\n  \n}', python: 'def two_sum(nums, target):\n    pass', cpp: 'vector<int> twoSum(vector<int>& nums, int target) {\n    \n}' },
  },
  {
    title: 'Valid Parentheses',
    slug: 'valid-parentheses',
    description: 'Given a string containing only (, ), {, }, [ and ], determine if the input string is valid. Brackets must close in the correct order.',
    difficulty: 'Easy', tags: ['Stack', 'String'],
    constraints: ['1 <= s.length <= 10^4', 's consists of parentheses only'],
    examples: [{ input: 's = "()[]{}"', output: 'true' }, { input: 's = "(]"', output: 'false' }],
    functionName: 'isValid',
    testCases: [
      { input: '["()[]{}"]', output: 'true', isHidden: false },
      { input: '["(]"]', output: 'false', isHidden: true },
      { input: '["([)]"]', output: 'false', isHidden: true },
    ],
    starterCode: { javascript: 'function isValid(s) {\n  \n}', python: 'def is_valid(s):\n    pass', cpp: 'bool isValid(string s) {\n    \n}' },
  },
  {
    title: 'Reverse String',
    slug: 'reverse-string',
    description: 'Write a function that reverses an array of characters in-place and returns the reversed array.',
    difficulty: 'Easy', tags: ['String', 'Two Pointers'],
    constraints: ['1 <= s.length <= 10^5', 's[i] is a printable ASCII character'],
    examples: [{ input: 's = ["h","e","l","l","o"]', output: '["o","l","l","e","h"]' }],
    functionName: 'reverseString',
    testCases: [
      { input: '[["h","e","l","l","o"]]', output: '["o","l","l","e","h"]', isHidden: false },
      { input: '[["H","a","n","n","a","h"]]', output: '["h","a","n","n","a","H"]', isHidden: true },
    ],
    starterCode: { javascript: 'function reverseString(s) {\n  \n}', python: 'def reverse_string(s):\n    pass', cpp: 'vector<char> reverseString(vector<char>& s) {\n    \n}' },
  },
  {
    title: 'Contains Duplicate',
    slug: 'contains-duplicate',
    description: 'Given an integer array, return true if any value appears at least twice, and false if every element is distinct.',
    difficulty: 'Easy', tags: ['Array', 'Hash Table'],
    constraints: ['1 <= nums.length <= 10^5', '-10^9 <= nums[i] <= 10^9'],
    examples: [{ input: 'nums = [1,2,3,1]', output: 'true' }, { input: 'nums = [1,2,3,4]', output: 'false' }],
    functionName: 'containsDuplicate',
    testCases: [
      { input: '[[1,2,3,1]]', output: 'true', isHidden: false },
      { input: '[[1,2,3,4]]', output: 'false', isHidden: true },
      { input: '[[1,1,1,3,3,4,3,2,4,2]]', output: 'true', isHidden: true },
    ],
    starterCode: { javascript: 'function containsDuplicate(nums) {\n  \n}', python: 'def contains_duplicate(nums):\n    pass', cpp: 'bool containsDuplicate(vector<int>& nums) {\n    \n}' },
  },
  {
    title: 'Valid Anagram',
    slug: 'valid-anagram',
    description: 'Given two strings s and t, return true if t is an anagram of s, and false otherwise.',
    difficulty: 'Easy', tags: ['String', 'Hash Table'],
    constraints: ['1 <= s.length, t.length <= 5 * 10^4', 's and t consist of lowercase English letters'],
    examples: [{ input: 's = "anagram", t = "nagaram"', output: 'true' }],
    functionName: 'isAnagram',
    testCases: [
      { input: '["anagram","nagaram"]', output: 'true', isHidden: false },
      { input: '["rat","car"]', output: 'false', isHidden: true },
    ],
    starterCode: { javascript: 'function isAnagram(s, t) {\n  \n}', python: 'def is_anagram(s, t):\n    pass', cpp: 'bool isAnagram(string s, string t) {\n    \n}' },
  },
  {
    title: 'Best Time to Buy and Sell Stock',
    slug: 'best-time-to-buy-sell-stock',
    description: 'Given an array of prices where prices[i] is the price of a stock on day i, return the maximum profit from one buy and one sell. Return 0 if no profit is possible.',
    difficulty: 'Easy', tags: ['Array', 'Greedy'],
    constraints: ['1 <= prices.length <= 10^5', '0 <= prices[i] <= 10^4'],
    examples: [{ input: 'prices = [7,1,5,3,6,4]', output: '5', explanation: 'Buy at 1, sell at 6' }],
    functionName: 'maxProfit',
    testCases: [
      { input: '[[7,1,5,3,6,4]]', output: '5', isHidden: false },
      { input: '[[7,6,4,3,1]]', output: '0', isHidden: true },
    ],
    starterCode: { javascript: 'function maxProfit(prices) {\n  \n}', python: 'def max_profit(prices):\n    pass', cpp: 'int maxProfit(vector<int>& prices) {\n    \n}' },
  },
  {
    title: 'Climbing Stairs',
    slug: 'climbing-stairs',
    description: 'You are climbing a staircase with n steps. You can climb 1 or 2 steps at a time. Return the number of distinct ways to reach the top.',
    difficulty: 'Easy', tags: ['Dynamic Programming'],
    constraints: ['1 <= n <= 45'],
    examples: [{ input: 'n = 3', output: '3', explanation: '1+1+1, 1+2, 2+1' }],
    functionName: 'climbStairs',
    testCases: [
      { input: '[3]', output: '3', isHidden: false },
      { input: '[2]', output: '2', isHidden: true },
      { input: '[10]', output: '89', isHidden: true },
    ],
    starterCode: { javascript: 'function climbStairs(n) {\n  \n}', python: 'def climb_stairs(n):\n    pass', cpp: 'int climbStairs(int n) {\n    \n}' },
  },
  {
    title: 'Binary Search',
    slug: 'binary-search',
    description: 'Given a sorted array of distinct integers and a target, return the index of target, or -1 if it does not exist. Solve in O(log n) time.',
    difficulty: 'Easy', tags: ['Array', 'Binary Search'],
    constraints: ['1 <= nums.length <= 10^4', 'All values are distinct', 'nums is sorted ascending'],
    examples: [{ input: 'nums = [-1,0,3,5,9,12], target = 9', output: '4' }],
    functionName: 'search',
    testCases: [
      { input: '[[-1,0,3,5,9,12],9]', output: '4', isHidden: false },
      { input: '[[-1,0,3,5,9,12],2]', output: '-1', isHidden: true },
    ],
    starterCode: { javascript: 'function search(nums, target) {\n  \n}', python: 'def search(nums, target):\n    pass', cpp: 'int search(vector<int>& nums, int target) {\n    \n}' },
  },
  {
    title: 'Palindrome Check',
    slug: 'palindrome-check',
    description: 'Given a string, return true if it is a palindrome, considering only alphanumeric characters and ignoring case.',
    difficulty: 'Easy', tags: ['String', 'Two Pointers'],
    constraints: ['1 <= s.length <= 2 * 10^5'],
    examples: [{ input: 's = "A man a plan a canal Panama"', output: 'true' }],
    functionName: 'isPalindrome',
    testCases: [
      { input: '["A man a plan a canal Panama"]', output: 'true', isHidden: false },
      { input: '["race a car"]', output: 'false', isHidden: true },
    ],
    starterCode: { javascript: 'function isPalindrome(s) {\n  \n}', python: 'def is_palindrome(s):\n    pass', cpp: 'bool isPalindrome(string s) {\n    \n}' },
  },
  {
    title: 'Merge Sorted Arrays',
    slug: 'merge-sorted-arrays',
    description: 'Given two sorted arrays nums1 and nums2, merge nums2 into nums1 in-place. nums1 has enough space at the end (filled with zeros) to hold all elements.',
    difficulty: 'Easy', tags: ['Array', 'Two Pointers'],
    constraints: ['nums1.length == m + n', '0 <= m, n <= 200'],
    examples: [{ input: 'nums1=[1,2,3,0,0,0], m=3, nums2=[2,5,6], n=3', output: '[1,2,2,3,5,6]' }],
    functionName: 'merge',
    testCases: [
      { input: '[[1,2,3,0,0,0],3,[2,5,6],3]', output: '[1,2,2,3,5,6]', isHidden: false },
      { input: '[[1],1,[],0]', output: '[1]', isHidden: true },
    ],
    starterCode: { javascript: 'function merge(nums1, m, nums2, n) {\n  \n}', python: 'def merge(nums1, m, nums2, n):\n    pass', cpp: 'void merge(vector<int>& nums1,int m,vector<int>& nums2,int n) {\n    \n}' },
  },
  {
    title: 'Missing Number',
    slug: 'missing-number',
    description: 'Given an array containing n distinct numbers in the range [0, n], return the only number in the range that is missing from the array.',
    difficulty: 'Easy', tags: ['Array', 'Math'],
    constraints: ['n == nums.length', '1 <= n <= 10^4', 'All numbers are unique'],
    examples: [{ input: 'nums = [3,0,1]', output: '2' }],
    functionName: 'missingNumber',
    testCases: [
      { input: '[[3,0,1]]', output: '2', isHidden: false },
      { input: '[[9,6,4,2,3,5,7,0,1]]', output: '8', isHidden: true },
    ],
    starterCode: { javascript: 'function missingNumber(nums) {\n  \n}', python: 'def missing_number(nums):\n    pass', cpp: 'int missingNumber(vector<int>& nums) {\n    \n}' },
  },
  {
    title: 'Reverse Linked List',
    slug: 'reverse-linked-list',
    description: 'Given the head of a singly linked list represented as an array, return the array reversed.',
    difficulty: 'Easy', tags: ['Linked List', 'Two Pointers'],
    constraints: ['0 <= length <= 5000'],
    examples: [{ input: 'list = [1,2,3,4,5]', output: '[5,4,3,2,1]' }],
    functionName: 'reverseList',
    testCases: [
      { input: '[[1,2,3,4,5]]', output: '[5,4,3,2,1]', isHidden: false },
      { input: '[[1,2]]', output: '[2,1]', isHidden: true },
    ],
    starterCode: { javascript: 'function reverseList(head) {\n  \n}', python: 'def reverse_list(head):\n    pass', cpp: 'vector<int> reverseList(vector<int>& head) {\n    \n}' },
  },
  {
    title: 'Count Vowels',
    slug: 'count-vowels',
    description: 'Given a string, return the number of vowels (a, e, i, o, u) it contains, case-insensitive.',
    difficulty: 'Easy', tags: ['String'],
    constraints: ['0 <= s.length <= 10^5'],
    examples: [{ input: 's = "Hello World"', output: '3' }],
    functionName: 'countVowels',
    testCases: [
      { input: '["Hello World"]', output: '3', isHidden: false },
      { input: '["aeiouAEIOU"]', output: '10', isHidden: true },
    ],
    starterCode: { javascript: 'function countVowels(s) {\n  \n}', python: 'def count_vowels(s):\n    pass', cpp: 'int countVowels(string s) {\n    \n}' },
  },
  {
    title: 'FizzBuzz',
    slug: 'fizzbuzz',
    description: 'Given an integer n, return an array of strings where: "FizzBuzz" if divisible by both 3 and 5, "Fizz" if divisible by 3, "Buzz" if divisible by 5, otherwise the number as a string.',
    difficulty: 'Easy', tags: ['Math', 'String'],
    constraints: ['1 <= n <= 10^4'],
    examples: [{ input: 'n = 5', output: '["1","2","Fizz","4","Buzz"]' }],
    functionName: 'fizzBuzz',
    testCases: [
      { input: '[5]', output: '["1","2","Fizz","4","Buzz"]', isHidden: false },
      { input: '[3]', output: '["1","2","Fizz"]', isHidden: true },
    ],
    starterCode: { javascript: 'function fizzBuzz(n) {\n  \n}', python: 'def fizz_buzz(n):\n    pass', cpp: 'vector<string> fizzBuzz(int n) {\n    \n}' },
  },
  {
    title: 'Power of Two',
    slug: 'power-of-two',
    description: 'Given an integer n, return true if it is a power of two.',
    difficulty: 'Easy', tags: ['Math', 'Bit Manipulation'],
    constraints: ['-2^31 <= n <= 2^31 - 1'],
    examples: [{ input: 'n = 16', output: 'true' }, { input: 'n = 3', output: 'false' }],
    functionName: 'isPowerOfTwo',
    testCases: [
      { input: '[16]', output: 'true', isHidden: false },
      { input: '[3]', output: 'false', isHidden: true },
      { input: '[1]', output: 'true', isHidden: true },
    ],
    starterCode: { javascript: 'function isPowerOfTwo(n) {\n  \n}', python: 'def is_power_of_two(n):\n    pass', cpp: 'bool isPowerOfTwo(int n) {\n    \n}' },
  },
  {
    title: 'Sum of Digits',
    slug: 'sum-of-digits',
    description: 'Given a non-negative integer, return the sum of its digits.',
    difficulty: 'Easy', tags: ['Math'],
    constraints: ['0 <= n <= 2^31 - 1'],
    examples: [{ input: 'n = 123', output: '6' }],
    functionName: 'sumOfDigits',
    testCases: [
      { input: '[123]', output: '6', isHidden: false },
      { input: '[9999]', output: '36', isHidden: true },
    ],
    starterCode: { javascript: 'function sumOfDigits(n) {\n  \n}', python: 'def sum_of_digits(n):\n    pass', cpp: 'int sumOfDigits(int n) {\n    \n}' },
  },
  {
    title: 'First Unique Character',
    slug: 'first-unique-character',
    description: 'Given a string, find the first non-repeating character and return its index. Return -1 if none exists.',
    difficulty: 'Easy', tags: ['String', 'Hash Table'],
    constraints: ['1 <= s.length <= 10^5', 's consists of only lowercase English letters'],
    examples: [{ input: 's = "leetcode"', output: '0' }, { input: 's = "aabb"', output: '-1' }],
    functionName: 'firstUniqChar',
    testCases: [
      { input: '["leetcode"]', output: '0', isHidden: false },
      { input: '["aabb"]', output: '-1', isHidden: true },
    ],
    starterCode: { javascript: 'function firstUniqChar(s) {\n  \n}', python: 'def first_uniq_char(s):\n    pass', cpp: 'int firstUniqChar(string s) {\n    \n}' },
  },
  {
    title: 'Intersection of Two Arrays',
    slug: 'intersection-of-two-arrays',
    description: 'Given two integer arrays, return an array of their intersection — elements that appear in both arrays. Each element in the result must be unique.',
    difficulty: 'Easy', tags: ['Array', 'Hash Table'],
    constraints: ['1 <= nums1.length, nums2.length <= 1000'],
    examples: [{ input: 'nums1=[1,2,2,1], nums2=[2,2]', output: '[2]' }],
    functionName: 'intersection',
    testCases: [
      { input: '[[1,2,2,1],[2,2]]', output: '[2]', isHidden: false },
      { input: '[[4,9,5],[9,4,9,8,4]]', output: '[9,4]', isHidden: true },
    ],
    starterCode: { javascript: 'function intersection(nums1, nums2) {\n  \n}', python: 'def intersection(nums1, nums2):\n    pass', cpp: 'vector<int> intersection(vector<int>& nums1, vector<int>& nums2) {\n    \n}' },
  },
  {
    title: 'Maximum Depth of Array Nesting',
    slug: 'max-depth-array-nesting',
    description: 'Given a flat array of integers representing a sequence, return the count of distinct even numbers.',
    difficulty: 'Easy', tags: ['Array'],
    constraints: ['1 <= nums.length <= 10^4'],
    examples: [{ input: 'nums = [2,4,3,6,2,8]', output: '4' }],
    functionName: 'countEven',
    testCases: [
      { input: '[[2,4,3,6,2,8]]', output: '4', isHidden: false },
      { input: '[[1,3,5]]', output: '0', isHidden: true },
    ],
    starterCode: { javascript: 'function countEven(nums) {\n  \n}', python: 'def count_even(nums):\n    pass', cpp: 'int countEven(vector<int>& nums) {\n    \n}' },
  },
  {
    title: 'Count Primes',
    slug: 'count-primes',
    description: 'Given an integer n, return the number of prime numbers strictly less than n.',
    difficulty: 'Easy', tags: ['Math'],
    constraints: ['0 <= n <= 5 * 10^6'],
    examples: [{ input: 'n = 10', output: '4', explanation: '2,3,5,7' }],
    functionName: 'countPrimes',
    testCases: [
      { input: '[10]', output: '4', isHidden: false },
      { input: '[0]', output: '0', isHidden: true },
    ],
    starterCode: { javascript: 'function countPrimes(n) {\n  \n}', python: 'def count_primes(n):\n    pass', cpp: 'int countPrimes(int n) {\n    \n}' },
  },
  // ─── MEDIUM ─────────────────────────────────────────────
  {
    title: 'Maximum Subarray',
    slug: 'maximum-subarray',
    description: 'Find the contiguous subarray with the largest sum and return its sum. (Kadane\'s algorithm)',
    difficulty: 'Medium', tags: ['Array', 'Dynamic Programming'],
    constraints: ['1 <= nums.length <= 10^5', '-10^4 <= nums[i] <= 10^4'],
    examples: [{ input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6', explanation: '[4,-1,2,1] has sum 6' }],
    functionName: 'maxSubArray',
    testCases: [
      { input: '[[-2,1,-3,4,-1,2,1,-5,4]]', output: '6', isHidden: false },
      { input: '[[1]]', output: '1', isHidden: true },
    ],
    starterCode: { javascript: 'function maxSubArray(nums) {\n  \n}', python: 'def max_sub_array(nums):\n    pass', cpp: 'int maxSubArray(vector<int>& nums) {\n    \n}' },
  },
  {
    title: 'Longest Substring Without Repeating Characters',
    slug: 'longest-substring-without-repeating-characters',
    description: 'Given a string, find the length of the longest substring without repeating characters.',
    difficulty: 'Medium', tags: ['String', 'Sliding Window', 'Hash Table'],
    constraints: ['0 <= s.length <= 5 * 10^4'],
    examples: [{ input: 's = "abcabcbb"', output: '3', explanation: '"abc"' }],
    functionName: 'lengthOfLongestSubstring',
    testCases: [
      { input: '["abcabcbb"]', output: '3', isHidden: false },
      { input: '["bbbbb"]', output: '1', isHidden: true },
    ],
    starterCode: { javascript: 'function lengthOfLongestSubstring(s) {\n  \n}', python: 'def length_of_longest_substring(s):\n    pass', cpp: 'int lengthOfLongestSubstring(string s) {\n    \n}' },
  },
  {
    title: 'Product of Array Except Self',
    slug: 'product-of-array-except-self',
    description: 'Return an array where each element is the product of all elements except itself. Solve in O(n) without division.',
    difficulty: 'Medium', tags: ['Array'],
    constraints: ['2 <= nums.length <= 10^5', '-30 <= nums[i] <= 30'],
    examples: [{ input: 'nums = [1,2,3,4]', output: '[24,12,8,6]' }],
    functionName: 'productExceptSelf',
    testCases: [
      { input: '[[1,2,3,4]]', output: '[24,12,8,6]', isHidden: false },
      { input: '[[-1,1,0,-3,3]]', output: '[0,0,9,0,0]', isHidden: true },
    ],
    starterCode: { javascript: 'function productExceptSelf(nums) {\n  \n}', python: 'def product_except_self(nums):\n    pass', cpp: 'vector<int> productExceptSelf(vector<int>& nums) {\n    \n}' },
  },
  {
    title: 'Group Anagrams',
    slug: 'group-anagrams',
    description: 'Given an array of strings, group the anagrams together and return the groups in any order.',
    difficulty: 'Medium', tags: ['String', 'Hash Table'],
    constraints: ['1 <= strs.length <= 10^4', '0 <= strs[i].length <= 100'],
    examples: [{ input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }],
    functionName: 'groupAnagrams',
    testCases: [
      { input: '[["eat","tea","tan","ate","nat","bat"]]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]', isHidden: false },
      { input: '[[""]]', output: '[[""]]', isHidden: true },
    ],
    starterCode: { javascript: 'function groupAnagrams(strs) {\n  \n}', python: 'def group_anagrams(strs):\n    pass', cpp: 'vector<vector<string>> groupAnagrams(vector<string>& strs) {\n    \n}' },
  },
  {
    title: 'Coin Change',
    slug: 'coin-change',
    description: 'Given an array of coin denominations and a total amount, return the fewest coins needed to make up the amount. Return -1 if it\'s impossible.',
    difficulty: 'Medium', tags: ['Dynamic Programming'],
    constraints: ['1 <= coins.length <= 12', '1 <= coins[i] <= 2^31 - 1', '0 <= amount <= 10^4'],
    examples: [{ input: 'coins = [1,5,11], amount = 15', output: '3' }],
    functionName: 'coinChange',
    testCases: [
      { input: '[[1,5,11],15]', output: '3', isHidden: false },
      { input: '[[2],3]', output: '-1', isHidden: true },
    ],
    starterCode: { javascript: 'function coinChange(coins, amount) {\n  \n}', python: 'def coin_change(coins, amount):\n    pass', cpp: 'int coinChange(vector<int>& coins, int amount) {\n    \n}' },
  },
  {
    title: 'Number of Islands',
    slug: 'number-of-islands',
    description: 'Given an m×n grid of "1"s (land) and "0"s (water), return the number of islands. An island is surrounded by water and formed by connecting adjacent land cells horizontally or vertically.',
    difficulty: 'Medium', tags: ['Graph', 'BFS', 'DFS'],
    constraints: ['1 <= grid.length, grid[i].length <= 300'],
    examples: [{ input: 'grid = [["1","1","0","0"],["1","1","0","0"],["0","0","1","0"],["0","0","0","1"]]', output: '3' }],
    functionName: 'numIslands',
    testCases: [
      { input: '[[["1","1","0","0"],["1","1","0","0"],["0","0","1","0"],["0","0","0","1"]]]', output: '3', isHidden: false },
      { input: '[[["1","1","1"],["0","1","0"],["1","1","1"]]]', output: '1', isHidden: true },
    ],
    starterCode: { javascript: 'function numIslands(grid) {\n  \n}', python: 'def num_islands(grid):\n    pass', cpp: 'int numIslands(vector<vector<char>>& grid) {\n    \n}' },
  },
  {
    title: 'Jump Game',
    slug: 'jump-game',
    description: 'Given an array where each element is your max jump length from that position, determine if you can reach the last index.',
    difficulty: 'Medium', tags: ['Array', 'Greedy'],
    constraints: ['1 <= nums.length <= 10^4', '0 <= nums[i] <= 10^5'],
    examples: [{ input: 'nums = [2,3,1,1,4]', output: 'true' }, { input: 'nums = [3,2,1,0,4]', output: 'false' }],
    functionName: 'canJump',
    testCases: [
      { input: '[[2,3,1,1,4]]', output: 'true', isHidden: false },
      { input: '[[3,2,1,0,4]]', output: 'false', isHidden: true },
    ],
    starterCode: { javascript: 'function canJump(nums) {\n  \n}', python: 'def can_jump(nums):\n    pass', cpp: 'bool canJump(vector<int>& nums) {\n    \n}' },
  },
  {
    title: 'Unique Paths',
    slug: 'unique-paths',
    description: 'A robot starts at the top-left of an m×n grid. It can only move right or down. Return the number of unique paths to reach the bottom-right corner.',
    difficulty: 'Medium', tags: ['Dynamic Programming', 'Math'],
    constraints: ['1 <= m, n <= 100'],
    examples: [{ input: 'm = 3, n = 7', output: '28' }],
    functionName: 'uniquePaths',
    testCases: [
      { input: '[3,7]', output: '28', isHidden: false },
      { input: '[3,2]', output: '3', isHidden: true },
    ],
    starterCode: { javascript: 'function uniquePaths(m, n) {\n  \n}', python: 'def unique_paths(m, n):\n    pass', cpp: 'int uniquePaths(int m, int n) {\n    \n}' },
  },
  {
    title: 'Rotate Array',
    slug: 'rotate-array',
    description: 'Given an integer array, rotate it to the right by k steps and return the result.',
    difficulty: 'Medium', tags: ['Array', 'Two Pointers'],
    constraints: ['1 <= nums.length <= 10^5', '0 <= k <= 10^5'],
    examples: [{ input: 'nums = [1,2,3,4,5,6,7], k = 3', output: '[5,6,7,1,2,3,4]' }],
    functionName: 'rotate',
    testCases: [
      { input: '[[1,2,3,4,5,6,7],3]', output: '[5,6,7,1,2,3,4]', isHidden: false },
      { input: '[[-1,-100,3,99],2]', output: '[3,99,-1,-100]', isHidden: true },
    ],
    starterCode: { javascript: 'function rotate(nums, k) {\n  \n}', python: 'def rotate(nums, k):\n    pass', cpp: 'vector<int> rotate(vector<int>& nums, int k) {\n    \n}' },
  },
  {
    title: 'Top K Frequent Elements',
    slug: 'top-k-frequent-elements',
    description: 'Given an integer array and integer k, return the k most frequent elements.',
    difficulty: 'Medium', tags: ['Array', 'Hash Table', 'Sorting'],
    constraints: ['1 <= nums.length <= 10^5', 'k is in range [1, number of unique elements]'],
    examples: [{ input: 'nums = [1,1,1,2,2,3], k = 2', output: '[1,2]' }],
    functionName: 'topKFrequent',
    testCases: [
      { input: '[[1,1,1,2,2,3],2]', output: '[1,2]', isHidden: false },
      { input: '[[1],1]', output: '[1]', isHidden: true },
    ],
    starterCode: { javascript: 'function topKFrequent(nums, k) {\n  \n}', python: 'def top_k_frequent(nums, k):\n    pass', cpp: 'vector<int> topKFrequent(vector<int>& nums, int k) {\n    \n}' },
  },
  {
    title: 'Spiral Matrix',
    slug: 'spiral-matrix',
    description: 'Given an m×n matrix, return all elements in spiral order.',
    difficulty: 'Medium', tags: ['Array', 'Matrix'],
    constraints: ['m == matrix.length', 'n == matrix[i].length', '1 <= m, n <= 10'],
    examples: [{ input: 'matrix = [[1,2,3],[4,5,6],[7,8,9]]', output: '[1,2,3,6,9,8,7,4,5]' }],
    functionName: 'spiralOrder',
    testCases: [
      { input: '[[[1,2,3],[4,5,6],[7,8,9]]]', output: '[1,2,3,6,9,8,7,4,5]', isHidden: false },
      { input: '[[[1,2],[3,4]]]', output: '[1,2,4,3]', isHidden: true },
    ],
    starterCode: { javascript: 'function spiralOrder(matrix) {\n  \n}', python: 'def spiral_order(matrix):\n    pass', cpp: 'vector<int> spiralOrder(vector<vector<int>>& matrix) {\n    \n}' },
  },
  {
    title: 'Subarray Sum Equals K',
    slug: 'subarray-sum-equals-k',
    description: 'Given an array of integers and an integer k, return the total number of subarrays whose sum equals k.',
    difficulty: 'Medium', tags: ['Array', 'Hash Table'],
    constraints: ['1 <= nums.length <= 2 * 10^4', '-1000 <= nums[i] <= 1000'],
    examples: [{ input: 'nums = [1,1,1], k = 2', output: '2' }],
    functionName: 'subarraySum',
    testCases: [
      { input: '[[1,1,1],2]', output: '2', isHidden: false },
      { input: '[[1,2,3],3]', output: '2', isHidden: true },
    ],
    starterCode: { javascript: 'function subarraySum(nums, k) {\n  \n}', python: 'def subarray_sum(nums, k):\n    pass', cpp: 'int subarraySum(vector<int>& nums, int k) {\n    \n}' },
  },
  {
    title: 'Letter Combinations of a Phone Number',
    slug: 'letter-combinations-phone-number',
    description: 'Given a string of digits from 2-9, return all possible letter combinations that the number could represent (like a phone keypad).',
    difficulty: 'Medium', tags: ['String', 'Backtracking'],
    constraints: ['0 <= digits.length <= 4', 'digits[i] is in [2..9]'],
    examples: [{ input: 'digits = "23"', output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' }],
    functionName: 'letterCombinations',
    testCases: [
      { input: '["23"]', output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]', isHidden: false },
      { input: '[""]', output: '[]', isHidden: true },
    ],
    starterCode: { javascript: 'function letterCombinations(digits) {\n  \n}', python: 'def letter_combinations(digits):\n    pass', cpp: 'vector<string> letterCombinations(string digits) {\n    \n}' },
  },
  {
    title: 'Permutations',
    slug: 'permutations',
    description: 'Given an array of distinct integers, return all possible permutations in any order.',
    difficulty: 'Medium', tags: ['Array', 'Backtracking'],
    constraints: ['1 <= nums.length <= 6', '-10 <= nums[i] <= 10', 'All integers are unique'],
    examples: [{ input: 'nums = [1,2,3]', output: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]' }],
    functionName: 'permute',
    testCases: [
      { input: '[[1,2,3]]', output: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]', isHidden: false },
      { input: '[[0,1]]', output: '[[0,1],[1,0]]', isHidden: true },
    ],
    starterCode: { javascript: 'function permute(nums) {\n  \n}', python: 'def permute(nums):\n    pass', cpp: 'vector<vector<int>> permute(vector<int>& nums) {\n    \n}' },
  },
  {
    title: 'Longest Palindromic Substring',
    slug: 'longest-palindromic-substring',
    description: 'Given a string, return the longest palindromic substring.',
    difficulty: 'Medium', tags: ['String', 'Dynamic Programming'],
    constraints: ['1 <= s.length <= 1000'],
    examples: [{ input: 's = "babad"', output: '"bab"' }],
    functionName: 'longestPalindrome',
    testCases: [
      { input: '["babad"]', output: '"bab"', isHidden: false },
      { input: '["cbbd"]', output: '"bb"', isHidden: true },
    ],
    starterCode: { javascript: 'function longestPalindrome(s) {\n  \n}', python: 'def longest_palindrome(s):\n    pass', cpp: 'string longestPalindrome(string s) {\n    \n}' },
  },
  {
    title: 'Search in Rotated Sorted Array',
    slug: 'search-in-rotated-sorted-array',
    description: 'A sorted array was rotated at an unknown pivot. Given a target, return its index or -1 if not present. Solve in O(log n).',
    difficulty: 'Medium', tags: ['Array', 'Binary Search'],
    constraints: ['1 <= nums.length <= 5000', 'All values are unique'],
    examples: [{ input: 'nums = [4,5,6,7,0,1,2], target = 0', output: '4' }],
    functionName: 'searchRotated',
    testCases: [
      { input: '[[4,5,6,7,0,1,2],0]', output: '4', isHidden: false },
      { input: '[[4,5,6,7,0,1,2],3]', output: '-1', isHidden: true },
    ],
    starterCode: { javascript: 'function searchRotated(nums, target) {\n  \n}', python: 'def search_rotated(nums, target):\n    pass', cpp: 'int searchRotated(vector<int>& nums, int target) {\n    \n}' },
  },
  {
    title: 'Merge Intervals',
    slug: 'merge-intervals',
    description: 'Given an array of intervals, merge all overlapping intervals and return the result.',
    difficulty: 'Medium', tags: ['Array', 'Sorting'],
    constraints: ['1 <= intervals.length <= 10^4'],
    examples: [{ input: 'intervals = [[1,3],[2,6],[8,10],[15,18]]', output: '[[1,6],[8,10],[15,18]]' }],
    functionName: 'merge',
    testCases: [
      { input: '[[[1,3],[2,6],[8,10],[15,18]]]', output: '[[1,6],[8,10],[15,18]]', isHidden: false },
      { input: '[[[1,4],[4,5]]]', output: '[[1,5]]', isHidden: true },
    ],
    starterCode: { javascript: 'function merge(intervals) {\n  \n}', python: 'def merge(intervals):\n    pass', cpp: 'vector<vector<int>> merge(vector<vector<int>>& intervals) {\n    \n}' },
  },
  {
    title: 'Three Sum',
    slug: 'three-sum',
    description: 'Given an array, find all unique triplets that sum to zero.',
    difficulty: 'Medium', tags: ['Array', 'Two Pointers', 'Sorting'],
    constraints: ['0 <= nums.length <= 3000', '-10^5 <= nums[i] <= 10^5'],
    examples: [{ input: 'nums = [-1,0,1,2,-1,-4]', output: '[[-1,-1,2],[-1,0,1]]' }],
    functionName: 'threeSum',
    testCases: [
      { input: '[[-1,0,1,2,-1,-4]]', output: '[[-1,-1,2],[-1,0,1]]', isHidden: false },
      { input: '[[0,1,1]]', output: '[]', isHidden: true },
    ],
    starterCode: { javascript: 'function threeSum(nums) {\n  \n}', python: 'def three_sum(nums):\n    pass', cpp: 'vector<vector<int>> threeSum(vector<int>& nums) {\n    \n}' },
  },
  {
    title: 'Task Scheduler',
    slug: 'task-scheduler',
    description: 'Given a list of tasks and a cooldown n between identical tasks, return the minimum number of intervals needed to finish all tasks.',
    difficulty: 'Medium', tags: ['Array', 'Greedy'],
    constraints: ['1 <= tasks.length <= 10^4', '0 <= n <= 100'],
    examples: [{ input: 'tasks = ["A","A","A","B","B","B"], n = 2', output: '8' }],
    functionName: 'leastInterval',
    testCases: [
      { input: '[["A","A","A","B","B","B"],2]', output: '8', isHidden: false },
      { input: '[["A","A","A","B","B","B"],0]', output: '6', isHidden: true },
    ],
    starterCode: { javascript: 'function leastInterval(tasks, n) {\n  \n}', python: 'def least_interval(tasks, n):\n    pass', cpp: 'int leastInterval(vector<char>& tasks, int n) {\n    \n}' },
  },
  {
    title: 'Decode Ways',
    slug: 'decode-ways',
    description: 'A message is encoded where "A"=1, "B"=2, ..., "Z"=26. Given a string of digits, return the number of ways to decode it.',
    difficulty: 'Medium', tags: ['String', 'Dynamic Programming'],
    constraints: ['1 <= s.length <= 100', 's contains only digits', 's may contain leading zeros'],
    examples: [{ input: 's = "226"', output: '3', explanation: '"BZ","VF","BBF"' }],
    functionName: 'numDecodings',
    testCases: [
      { input: '["226"]', output: '3', isHidden: false },
      { input: '["06"]', output: '0', isHidden: true },
    ],
    starterCode: { javascript: 'function numDecodings(s) {\n  \n}', python: 'def num_decodings(s):\n    pass', cpp: 'int numDecodings(string s) {\n    \n}' },
  },
  // ─── HARD ───────────────────────────────────────────────
  {
    title: 'Trapping Rain Water',
    slug: 'trapping-rain-water',
    description: 'Given an elevation map as an array, compute how much water can be trapped between the bars after raining.',
    difficulty: 'Hard', tags: ['Array', 'Two Pointers', 'Dynamic Programming'],
    constraints: ['n == height.length', '1 <= n <= 2 * 10^4', '0 <= height[i] <= 10^5'],
    examples: [{ input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' }],
    functionName: 'trap',
    testCases: [
      { input: '[[0,1,0,2,1,0,1,3,2,1,2,1]]', output: '6', isHidden: false },
      { input: '[[4,2,0,3,2,5]]', output: '9', isHidden: true },
    ],
    starterCode: { javascript: 'function trap(height) {\n  \n}', python: 'def trap(height):\n    pass', cpp: 'int trap(vector<int>& height) {\n    \n}' },
  },
  {
    title: 'Median of Two Sorted Arrays',
    slug: 'median-of-two-sorted-arrays',
    description: 'Given two sorted arrays, return the median of the combined array. Solve in O(log(m+n)) time.',
    difficulty: 'Hard', tags: ['Array', 'Binary Search', 'Divide and Conquer'],
    constraints: ['nums1.length == m', 'nums2.length == n', '0 <= m, n <= 1000'],
    examples: [{ input: 'nums1 = [1,3], nums2 = [2]', output: '2.0' }],
    functionName: 'findMedianSortedArrays',
    testCases: [
      { input: '[[1,3],[2]]', output: '2', isHidden: false },
      { input: '[[1,2],[3,4]]', output: '2.5', isHidden: true },
    ],
    starterCode: { javascript: 'function findMedianSortedArrays(nums1, nums2) {\n  \n}', python: 'def find_median_sorted_arrays(nums1, nums2):\n    pass', cpp: 'double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n    \n}' },
  },
  {
    title: 'Longest Valid Parentheses',
    slug: 'longest-valid-parentheses',
    description: 'Given a string containing only ( and ), return the length of the longest valid parentheses substring.',
    difficulty: 'Hard', tags: ['String', 'Stack', 'Dynamic Programming'],
    constraints: ['0 <= s.length <= 3 * 10^4'],
    examples: [{ input: 's = ")()())"', output: '4' }],
    functionName: 'longestValidParentheses',
    testCases: [
      { input: '[")()())"]', output: '4', isHidden: false },
      { input: '[""]', output: '0', isHidden: true },
    ],
    starterCode: { javascript: 'function longestValidParentheses(s) {\n  \n}', python: 'def longest_valid_parentheses(s):\n    pass', cpp: 'int longestValidParentheses(string s) {\n    \n}' },
  },
  {
    title: 'N-Queens',
    slug: 'n-queens',
    description: 'Place n queens on an n×n chessboard such that no two queens attack each other. Return all distinct solutions.',
    difficulty: 'Hard', tags: ['Array', 'Backtracking'],
    constraints: ['1 <= n <= 9'],
    examples: [{ input: 'n = 4', output: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]' }],
    functionName: 'solveNQueens',
    testCases: [
      { input: '[4]', output: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]', isHidden: false },
      { input: '[1]', output: '[["Q"]]', isHidden: true },
    ],
    starterCode: { javascript: 'function solveNQueens(n) {\n  \n}', python: 'def solve_n_queens(n):\n    pass', cpp: 'vector<vector<string>> solveNQueens(int n) {\n    \n}' },
  },
  {
    title: 'Minimum Window Substring',
    slug: 'minimum-window-substring',
    description: 'Given strings s and t, return the minimum window substring of s that contains all characters of t. Return "" if none exists.',
    difficulty: 'Hard', tags: ['String', 'Sliding Window', 'Hash Table'],
    constraints: ['1 <= s.length, t.length <= 10^5'],
    examples: [{ input: 's = "ADOBECODEBANC", t = "ABC"', output: '"BANC"' }],
    functionName: 'minWindow',
    testCases: [
      { input: '["ADOBECODEBANC","ABC"]', output: '"BANC"', isHidden: false },
      { input: '["a","aa"]', output: '""', isHidden: true },
    ],
    starterCode: { javascript: 'function minWindow(s, t) {\n  \n}', python: 'def min_window(s, t):\n    pass', cpp: 'string minWindow(string s, string t) {\n    \n}' },
  },
  {
    title: 'Word Ladder',
    slug: 'word-ladder',
    description: 'Given beginWord, endWord, and a word list, return the length of the shortest transformation sequence from beginWord to endWord, changing one letter at a time. Each intermediate word must be in the word list.',
    difficulty: 'Hard', tags: ['BFS', 'Hash Table', 'Graph'],
    constraints: ['1 <= beginWord.length <= 10', 'endWord and all wordList words have same length'],
    examples: [{ input: 'beginWord="hit", endWord="cog", wordList=["hot","dot","dog","lot","log","cog"]', output: '5' }],
    functionName: 'ladderLength',
    testCases: [
      { input: '["hit","cog",["hot","dot","dog","lot","log","cog"]]', output: '5', isHidden: false },
      { input: '["hit","cog",["hot","dot","dog","lot","log"]]', output: '0', isHidden: true },
    ],
    starterCode: { javascript: 'function ladderLength(beginWord, endWord, wordList) {\n  \n}', python: 'def ladder_length(begin_word, end_word, word_list):\n    pass', cpp: 'int ladderLength(string beginWord, string endWord, vector<string>& wordList) {\n    \n}' },
  },
  {
    title: 'Serialize and Deserialize Binary Tree',
    slug: 'serialize-deserialize-binary-tree',
    description: 'Design an algorithm to serialize a binary tree (given as an array) to a string and deserialize it back to the original array.',
    difficulty: 'Hard', tags: ['Tree', 'BFS', 'Design'],
    constraints: ['0 <= number of nodes <= 10^4'],
    examples: [{ input: 'root = [1,2,3,null,null,4,5]', output: '[1,2,3,null,null,4,5]' }],
    functionName: 'serializeDeserialize',
    testCases: [
      { input: '[[[1,2,3,null,null,4,5]]]', output: '[1,2,3,null,null,4,5]', isHidden: false },
    ],
    starterCode: { javascript: 'function serializeDeserialize(tree) {\n  // serialize and deserialize\n  return tree;\n}', python: 'def serialize_deserialize(tree):\n    return tree', cpp: 'vector<int> serializeDeserialize(vector<int> tree) {\n    return tree;\n}' },
  },
  {
    title: 'Largest Rectangle in Histogram',
    slug: 'largest-rectangle-in-histogram',
    description: 'Given an array of bar heights in a histogram, find the area of the largest rectangle that can be formed.',
    difficulty: 'Hard', tags: ['Array', 'Stack'],
    constraints: ['1 <= heights.length <= 10^5', '0 <= heights[i] <= 10^4'],
    examples: [{ input: 'heights = [2,1,5,6,2,3]', output: '10' }],
    functionName: 'largestRectangleArea',
    testCases: [
      { input: '[[2,1,5,6,2,3]]', output: '10', isHidden: false },
      { input: '[[2,4]]', output: '4', isHidden: true },
    ],
    starterCode: { javascript: 'function largestRectangleArea(heights) {\n  \n}', python: 'def largest_rectangle_area(heights):\n    pass', cpp: 'int largestRectangleArea(vector<int>& heights) {\n    \n}' },
  },
  {
    title: 'Regular Expression Matching',
    slug: 'regular-expression-matching',
    description: 'Implement regular expression matching with support for "." (any single character) and "*" (zero or more of the preceding element).',
    difficulty: 'Hard', tags: ['String', 'Dynamic Programming', 'Recursion'],
    constraints: ['1 <= s.length <= 20', '1 <= p.length <= 30'],
    examples: [{ input: 's = "aa", p = "a*"', output: 'true' }],
    functionName: 'isMatch',
    testCases: [
      { input: '["aa","a*"]', output: 'true', isHidden: false },
      { input: '["mississippi","mis*is*p*."]', output: 'false', isHidden: true },
    ],
    starterCode: { javascript: 'function isMatch(s, p) {\n  \n}', python: 'def is_match(s, p):\n    pass', cpp: 'bool isMatch(string s, string p) {\n    \n}' },
  },
  {
    title: 'Sudoku Solver',
    slug: 'sudoku-solver',
    description: 'Given a partially filled 9×9 Sudoku board (represented as a flat 81-element array with 0 for empty), return the solved board.',
    difficulty: 'Hard', tags: ['Array', 'Backtracking', 'Matrix'],
    constraints: ['Board is always 9×9', 'Input is guaranteed to have exactly one valid solution'],
    examples: [{ input: 'board = [5,3,0,0,7,0,0,0,0,...]', output: '[5,3,4,6,7,8,9,1,2,...]' }],
    functionName: 'solveSudoku',
    testCases: [
      {
        input: '[[[5,3,0,0,7,0,0,0,0],[6,0,0,1,9,5,0,0,0],[0,9,8,0,0,0,0,6,0],[8,0,0,0,6,0,0,0,3],[4,0,0,8,0,3,0,0,1],[7,0,0,0,2,0,0,0,6],[0,6,0,0,0,0,2,8,0],[0,0,0,4,1,9,0,0,5],[0,0,0,0,8,0,0,7,9]]]',
        output: '[[5,3,4,6,7,8,9,1,2],[6,7,2,1,9,5,3,4,8],[1,9,8,3,4,2,5,6,7],[8,5,9,7,6,1,4,2,3],[4,2,6,8,5,3,7,9,1],[7,1,3,9,2,4,8,5,6],[9,6,1,5,3,7,2,8,4],[2,8,7,4,1,9,6,3,5],[3,4,5,2,8,6,1,7,9]]',
        isHidden: false
      },
    ],
    starterCode: { javascript: 'function solveSudoku(board) {\n  \n}', python: 'def solve_sudoku(board):\n    pass', cpp: 'vector<vector<int>> solveSudoku(vector<vector<int>>& board) {\n    \n}' },
  },
];

const seed = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  await Problem.deleteMany();
  await Problem.insertMany(problems);
  console.log(`${problems.length} problems seeded`);
  process.exit();
};

seed();